<tr>
  <td>

<!-- begin of Top100 code -->

<script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?2820201"></script>
<noscript>
<a href="http://top100.rambler.ru/navi/2820201/">
<img src="http://counter.rambler.ru/top100.cnt?2820201" alt="Rambler's Top100" border="0" />
</a>

</noscript>
<!-- end of Top100 code -->

<!--Openstat-->
<span id="openstat2294626"></span>
<script type="text/javascript">
var openstat = { counter: 2294626, image: 5083, color: "458efc", next: openstat, track_links: "all" };
(function(d, t, p) {
var j = d.createElement(t); j.async = true; j.type = "text/javascript";
j.src = ("https:" == p ? "https:" : "http:") + "//openstat.net/cnt.js";
var s = d.getElementsByTagName(t)[0]; s.parentNode.insertBefore(j, s);
})(document, "script", document.location.protocol);
</script>
<!--/Openstat-->

<!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t18.11;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";"+Math.random()+
"' alt='' title='LiveInternet: показано число просмотров за 24"+
" часа, посетителей за 24 часа и за сегодня' "+
"border='0' width='88' height='31'><\/a>")
//--></script><!--/LiveInternet-->

  </td>
  <td class="footertabletextcontainer" align="center">Материалы сайта предназначены для лиц 18 лет и старше<br>The noon &copy; 2014</td>
  <td>&nbsp;</td>
</tr>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter20282218 = new Ya.Metrika({id:20282218,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/20282218" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<script async="async" src="https://w.uptolike.com/widgets/v1/zp.js?pid=930673" type="text/javascript"></script>

<!--
<div id="RTBDIV_8659"> 
        <div id="RTBPL_8659"> 
            <a href="http://rtbsystem.com/ru/advertiser/request"></a>
        </div> 
</div> 
<script type="text/javascript"> 
    if (document.getElementById('RTBDIV_8659')) { 
        var RtbSystemDate = new Date(); 
        document.write('<scr'+'ipt type="text/javascript" async ' 
            +'src="http://code.rtbsystem.com/8659.js?t='+RtbSystemDate.getYear()+RtbSystemDate.getMonth() 
            +RtbSystemDate.getDay()+RtbSystemDate.getHours() + '" charset="utf-8" ></scr'+'ipt>'); 
    } 
</script>
-->

<script charset="windows-1251" type="text/javascript" src="http://code.directadvert.ru/show.cgi?adp=112534&div=DIV_DA_112534"></script>