<table class="menu">
  <tr height=20>
    <td class="tm"><a class="ml" href="/">Загрузка</a></td>
    <td class="ml">::</td>
    <td class="tm"><a class="ml" href="/multiple.php">Мультизагрузка</a></td>
    <td class="ml">::</td>
    <td class="tm"><a class="ml2" href="/install.exe">Клиент</a></td>
    <td class="ml">::</td>
    <td class="tm"><a class="ml" href="/galery.php">Галереи</a></td>
    <td class="ml">::</td>
    <td class="tm"><a class="ml" href="/contact.php">Контакты</a></td>
    <td class="ml">::</td>
    <td class="tm"><a class="ml" href="/rules.php">Правила</a></td>
    <td class="ml">&nbsp</td>
    <td class="ml" width='100%' align='right'>
<!--
      <form action="/search.php">
        <input type="text" id="srch" name="q" style="width: 210px">
        <input type="submit" value="Найти">
      </form>
-->
    </td>
  </tr>
</tbody></table>