<!-- Put this script tag to the <head> of your page -->
<script type="text/javascript" src="//vk.com/js/api/openapi.js?79"></script>

<script type="text/javascript">
  VK.init({apiId: 3453363, onlyWidgets: true});
</script>

<!-- Put this div tag to the place, where the Poll block will be -->
<div id="vk_poll"></div>
<script type="text/javascript">
VK.Widgets.Poll("vk_poll", {width: "300", pageUrl: "http://file-up.net"}, "76828572_40648668cf8ac090e9");
</script>
