<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.11.1deb1 setup script
 * Date: Wed, 02 Jan 2013 08:16:19 +0100
 */

/* Servers configuration */
$i = 0;

/* Server: master [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'master';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '/var/run/mysqld/mysqld.sock';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['ssl'] = true;

/* Server: slave [2] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'slave';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3307;
$cfg['Servers'][$i]['socket'] = '/var/run/mysqld/mysqld2.sock';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '50e3dcddeb98e0.80753728';
$cfg['DefaultLang'] = 'ru';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>