#! /bin/sh

### BEGIN INIT INFO
# Provides:          noon_cron
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       starts Noon cron
### END INIT INFO

# Install: 
#   1. Copy this file to /etc/init.d
#   2. Edit the variables below
#   3. run "update-rc.d noon_cron defaults"

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=noon_cron
DAEMON=/root/start_daemon.sh
PID_FILE=/tmp/daemon_pid

# --------------------------------------------------------------
# No edits necessary beyond this line
# --------------------------------------------------------------

if [ ! -x $DAEMON ]; then
	echo "File not found or is not executable: $DAEMON!"
	exit 0
fi

status() {
	if [ ! -r $PID_FILE ]; then
		return 1
	fi
	
	return 0
}
	
start() {
	if status; then
		echo "Noon cron is already running!"
		exit 1
	else
		nohup $DAEMON &>/dev/null
	fi
}

stop () {	
	if ! status; then
		echo "No PID-file at $PID_FILE found or PID not valid. Maybe not running"
		exit 1
	fi
	
        kill -9 `cat /tmp/daemon_pid`
        rm -f /tmp/daemon_pid
}

case "$1" in
	start)
		echo "Starting $NAME: "
		start
		echo "... DONE"
	;;

	stop)
		echo "Stopping $NAME: "
		stop
		echo "... DONE"
	;;

	force-reload|restart)
		echo "Stopping $NAME: "
		stop
		echo "Starting $NAME: "
		start
		echo "... DONE"
	;;
	
	status)
		if status; then
			echo "Noon cron is RUNNING"
		else
			echo "Noon cron is NOT RUNNING"
		fi
	;;
	
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

exit 0
