#!/bin/sh
set -e

test -d /var/spool/squirrelmail/attach || exit 0

cd /var/spool/squirrelmail/attach

find \
         -maxdepth 1 \
         -xdev \
         -type f \
         \! -name '*.*' \
         \! -name '*_*' \
         -atime +2 \
         -print0 \
| xargs \
         -0 \
         --no-run-if-empty \
         rm --

